---
test_networks:
  test1:
    group: tinc_test1
    main_conf:
      ConnectTo: [instance1, instance2]
      Device: /dev/net/tun
      Interface: test1
    host_conf:
      Address: "{{ inventory_hostname }}"
      Subnet: 10.0.0.2/32
  test2:
    group: tinc_test1
    main_conf:
      ConnectTo: [instance1, instance2]
      Device: /dev/net/tun
      Interface: test2
    host_conf:
      Address: "{{ inventory_hostname }}"
      Port: 656
      Subnet: 10.0.0.4/32
