---
test_networks:
  test1:
    group: tinc_test1
    main_conf:
      ConnectTo: [instance1, instance2]
      Device: /dev/net/tun
      Interface: test1
    host_conf:
      Address: "{{ inventory_hostname }}"
      Subnet: 10.0.0.2/32
    scripts:
      tinc-up: |
        #!/usr/bin/env bash
        ip address add dev "$INTERFACE" 10.0.0.2/32
        ip link set up "$INTERFACE"
      subnet-up: |
        #!/usr/bin/env bash
        ip route add "$SUBNET" dev "$INTERFACE"
  test2:
    group: tinc_test1
    main_conf:
      ConnectTo: [instance1, instance2]
      Device: /dev/net/tun
      Interface: test2
    host_conf:
      Address: "{{ inventory_hostname }}"
      Port: 656
      Subnet: 10.0.0.4/32
    scripts:
      tinc-up: |
        #!/usr/bin/env bash
        ip address add dev "$INTERFACE" 10.0.0.4/32
        ip link set up "$INTERFACE"
      subnet-up: |
        #!/usr/bin/env bash
        ip route add "$SUBNET" dev "$INTERFACE"
