---
- name: "Restart tinc instance {{ tinc_network_name }}"
  service:
    name: "{{ tinc_service }}{{ tinc_network_name }}"
    state: restarted
  when: tinc_restart and tinc_state != 'stopped'
  register: tinc_restart_
  listen:
    - Restart tinc

- name: "Reload tinc instance {{ tinc_network_name }}"
  service:
    name: "{{ tinc_service }}{{ tinc_network_name }}"
    state: reloaded
  when: >
    tinc_reload and tinc_state != 'stopped'
    and (tinc_restart_ is not defined or
         tinc_restart_ is not changed)
