---
- hosts: all
  tasks:
    - import_role:
        name: tinc
      vars:
        tinc_network_name: "test1"
        tinc_group: "{{ test_networks.test1.group }}"
        tinc_main_conf: "{{ test_networks.test1.main_conf }}"
        tinc_host_conf: "{{ test_networks.test1.host_conf }}"
        tinc_scripts: "{{ test_networks.test1.scripts }}"

    - import_role:
        name: tinc
      vars:
        tinc_network_name: "test2"
        tinc_group: "{{ test_networks.test2.group }}"
        tinc_main_conf: "{{ test_networks.test2.main_conf }}"
        tinc_host_conf: "{{ test_networks.test2.host_conf }}"
        tinc_scripts: "{{ test_networks.test2.scripts }}"
